version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tend_db
      POSTGRES_USER: tend_user
      POSTGRES_PASSWORD: tend_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://tend_user:tend_password@db:5432/tend_db
      - REDIS_URL=redis://redis:6379/0
    working_dir: /app/tend_project
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: